1>------ Build started: Project: inheritance, Configuration: Debug Win32 ------
1>Compiling...
1>inheritance.cpp
1>Linking...
1>LINK : C:\Users\hp\Documents\Visual Studio 2008\Projects\inheritance\Debug\inheritance.exe not found or not built by the last incremental link; performing full link
1>Embedding manifest...
1>Build log was saved at "file://c:\Users\hp\Documents\Visual Studio 2008\Projects\inheritance\inheritance\Debug\BuildLog.htm"
1>inheritance - 0 error(s), 0 warning(s)
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
